name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"
      - name: Restore dependencies
        working-directory: GarbageCan
        run: dotnet restore
      - name: Build
        working-directory: GarbageCan
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test
        working-directory: GarbageCan.Application.UnitTests
      - name: Deploy
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "garbage-can"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
